export const FETCH_BEGIN = 'FETCH_BEGIN';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';

export const FETCH_CATCHED_BEGIN = 'FETCH_CATCHED_BEGIN';
export const FETCH_CATCHED_SUCCESS = 'FETCH_CATCHED_SUCCESS';
export const FETCH_CATCHED_FAILURE = 'FETCH_CATCHED_FAILURE';

export const CATCH_SUCCESS = 'CATCH_SUCCESS';
export const CATCH_FAILURE = 'CATCH_FAILURE';

export const FETCH_POKE = 'FETCH_POKE';
export const FETCH_POKE_SUCCESS = 'FETCH_POKE_SUCCESS';
export const FETCH_POKE_FAILURE = 'FETCH_POKE_FAILURE';

export const ADD_CATCHED = 'ADD_CATCHED';

export const FETCHED_ALL_POKEMONS = 'FETCHED_ALL_POKEMONS';
export const FETCHED_ALL_CATCHED = 'FETCHED_ALL_CATCHED';


